name: Update Container on Portainer

on:
  push:
    branches:
      - development

jobs:
  update-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Iniciando la construcción y el empuje de la imagen Docker..."
          docker build -t socialworky/worky-message-dev:${{ github.sha }} .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push socialworky/worky-message-dev:${{ github.sha }}
          echo "Construcción y empuje de la imagen Docker completados."

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: https://portainer-dev.worky.cl
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack-name: 'worky-message-dev'
          stack-definition: 'docker-compose-worky.dev.yml'
          image: socialworky/worky-message-dev:${{ github.sha }}
        env:
          GIT_SHA: ${{ github.sha }}
